### ISSUE TITLE
attention to jfoenix 

### ISSUE THREAD

**Issue by aminabs** [Kairos-Project/kairos-material-components#3]
Hi,
I've a question for you :)
The activity based development is an awesome idea for javafx developers. However, I think you may take jfoenix components into consideration when implementing your material components. I want to know what's the difference between your components project and that of jfoenix?

**Comment by marconi1992** [comment]
HI,
Wow JFoenix is an awesome material library, but did not know about her library. About the difference, JFoenix has an complete set of controls, but Kairos has layouts that work like android. e.g . DrawerLayout, RecyclerView, SlidingTabLayout, and also sync the toolbar behavior with an  activity. Kairos could separate both package in differents repositories to provide to the developer the oportunnity to work with Kairos layouts and  JFoenix components.

**Comment by aminabs** [comment]
Great to join them alltogether.
Btw, I have been working on the same idea as your android like framework
since last year. The project is pretty complete, but not an open source
one. Hope to see your job in action.

**Comment by ruifung** [comment]
Why not use them both together? I mean, given that the components can technically be used as stanalone javafx components... so it works fine.
